In [2]:
import pandas as pd
import numpy as np
import glob
import datetime

In [3]:
dates_list = glob.glob("../data/data_Chatta/*")

In [4]:
column_names = ['pickup_node', 'pickup_lon', 'pickup_lat', 'dropoff_node', 'dropoff_lon', 'dropoff_lat', 'time']
request_df = pd.DataFrame()
for date in dates_list:
    day_df = pd.read_csv(date+'/requests/requests.csv', names = column_names)
    date_str = date.split('/')[-1]
    month, day = date_str.split('-')
    date_str = datetime.datetime(2021, int(month), int(day), 0, 0, 0).date()
    day_df['date'] = date_str
    request_df = request_df.append(day_df)

In [6]:
request_df = request_df.reset_index(drop=True)

In [7]:
request_df

,pickup_node,pickup_lon,pickup_lat,dropoff_node,dropoff_lon,dropoff_lat,time,date
0,227,-85.306430,35.034652,2883,-85.323744,35.014915,5:15:00,2021-03-23
1,9100,-85.140255,35.022523,8494,-85.155498,35.083075,5:45:00,2021-03-23
2,6514,-85.230477,35.068162,6256,-85.277882,35.047528,6:15:00,2021-03-23
3,1891,-85.248044,35.130586,10153,-85.245980,35.133695,6:30:00,2021-03-23
4,6665,-85.276830,35.040614,4909,-85.373273,35.019111,7:00:00,2021-03-23
...,...,...,...,...,...,...,...,...
5152,9661,-85.163894,35.043990,3143,-85.139730,35.042317,20:00:00,2021-05-11
5153,223,-85.155002,35.031228,5084,-85.261947,35.035251,20:10:00,2021-05-11
5154,8559,-85.177323,35.051690,223,-85.155002,35.031228,21:15:00,2021-05-11
5155,4621,-85.292208,35.048419,4520,-85.253544,35.069096,22:00:00,2021-05-11
5156,4909,-85.373273,35.019111,10356,-85.169322,35.016188,23:00:00,2021-05-11

In [8]:
request_df.to_csv('../data/data/requests/requests_100.csv', header = False)